DROP TABLE IF EXISTS Tasks;
DROP TABLE IF EXISTS Reminders;
DROP TABLE IF EXISTS Projects;
DROP TABLE IF EXISTS Calendars;
DROP TABLE IF EXISTS LastEdits;

DROP TABLE IF EXISTS repository;
DROP TABLE IF EXISTS milestone;
DROP TABLE IF EXISTS issue;
DROP TABLE IF EXISTS milestoneRegistry;